### PR TITLE
updated indexes

### PR DESCRIPTION
**Pull request by neazen**
index for last csgo update yes (I'm retarded with github idk what I'm even doing)

### CODE REVIEW

**Comment by twangsriprasoet** [comment]
how can i update the indexes by myself in the future? and where can i get the indexes from?

**Comment by neazen** [comment]
> how can i update the indexes by myself in the future? and where can i get the indexes from?

you can get them from [here](https://www.unknowncheats.me/forum/counterstrike-global-offensive/103220-counterstrike-global-offensive-reversal-structs-offsets.html) (check latest pages) or from some discords

**Comment by twangsriprasoet** [comment]
i've found it and updated indexes already but thank you!

**Comment by neazen** [comment]
kk

**Pull request closed without merging**
